'on':
  - pull_request
jobs:
  annotate_pull_request:
    runs-on: ubuntu-latest
    name: perform annotation
    steps:
      - name: annotation action step
        id: annotation
        uses: kherin/review-app-action@v1
        with:
          annotation-title: Blogar Review App
          annotation-url: 'https://blogar-demo-app.com'
